
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Aug 24 14:59:25 CEST 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACKET = 33;
  public static final int INCREMENT = 36;
  public static final int CONST = 3;
  public static final int LOGICOR = 31;
  public static final int CONTINUE = 42;
  public static final int GREATER = 38;
  public static final int LPAREN = 8;
  public static final int SEMI = 7;
  public static final int DECREMENT = 40;
  public static final int FOR = 22;
  public static final int MINUS = 29;
  public static final int RPAREN = 9;
  public static final int LOGICEQ = 30;
  public static final int COMMA = 10;
  public static final int DIV = 28;
  public static final int MULTIPLY = 43;
  public static final int LESSER = 32;
  public static final int PLUS = 13;
  public static final int IF = 20;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int RBRACKET = 39;
  public static final int EQUAL = 14;
  public static final int NEW = 24;
  public static final int error = 1;
  public static final int BOOLS = 18;
  public static final int NUMBER = 16;
  public static final int BREAK = 34;
  public static final int IDENT = 17;
  public static final int LOGICAND = 37;
  public static final int VOID = 15;
  public static final int LESSEREQ = 41;
  public static final int LBRACE = 5;
  public static final int ELSE = 21;
  public static final int READ = 35;
  public static final int ENUM = 2;
  public static final int CHARCONST = 19;
  public static final int RBRACE = 6;
  public static final int PROG = 4;
  public static final int GREATEREQ = 25;
  public static final int LOGICNEQ = 27;
  public static final int MODUO = 23;
  public static final int PRINT = 11;
}

