
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Dec 17 14:22:56 CET 2017
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym_old {
  /* terminals */
  public static final int BREAK=18; //
  public static final int CLASS=19; //
  public static final int INTERFACE=20; //
  public static final int ENUM=21; //
  public static final int CONST=22; //
  public static final int NEW=24; //
  public static final int READ=25; //
  public static final int FOR=26; //
  public static final int EXTENDS=27; //
  public static final int CONTINUE=28; //
  public static final int LOGICEQ=31; // //
  public static final int DIV=32; // //
  public static final int MODUO=33; // //
  public static final int LOGICNEQ=34; // //
  public static final int GREATER=35; // //
  public static final int GREATEREQ=36; // //
  public static final int LESSER=37; // //
  public static final int LESSEREQ=38; // //
  public static final int LOGICAND=39; // //
  public static final int LOGICOR=40; // //
  public static final int INCREMENT=41; // //
  public static final int DECREMENT=42; // //
  public static final int MINUS=43; // //
  public static final int LBRACKET=44; // //
  public static final int RBRACKET=45; // //
  public static final int DOT=46; // //
  public static final int ELSE = 17;
  public static final int IDENT = 15;
  public static final int PLUS = 11;
  public static final int CHARCONST = 30;
  public static final int BOOLS = 29;
  public static final int RBRACE = 4;
  public static final int RPAREN = 7;
  public static final int EQUAL = 12;
  public static final int SEMI = 5;
  public static final int RETURN = 10;
  public static final int IF = 16;
  public static final int LPAREN = 6;
  public static final int LBRACE = 3;
  public static final int COMMA = 8;
  public static final int EOF = 0;
  public static final int NUMBER = 14;
  public static final int PROG = 2;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int VOID = 13;
}

